/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sig.view;

import sig.controller.ListenerOnInvoices;
import sig.controller.ListenerOnTableSelection;
import sig.model.HeaderOfInvoice;
import sig.model.HeaderOfInvoiceTableModel;
import sig.model.LinesOfInvoice;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;

public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form InvoiceFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        InvoiceTableMain = new javax.swing.JTable();
        CreateNewInvoicebtn = new javax.swing.JButton();
        deleteInvoicebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cutomerNameLabel = new javax.swing.JLabel();
        InvoiceDateLable = new javax.swing.JLabel();
        InvoiceNumLabel = new javax.swing.JLabel();
        InvoiceTotalLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        InvoicedetailLabel = new javax.swing.JTable();
        createNewLinebtn = new javax.swing.JButton();
        deleteLinebtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        LoadoptionItem = new javax.swing.JMenuItem();
        SaveoptionItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InvoiceTableMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        InvoiceTableMain.getSelectionModel().addListSelectionListener(selectionListener);
        jScrollPane1.setViewportView(InvoiceTableMain);

        CreateNewInvoicebtn.setText("New Invoice");
        CreateNewInvoicebtn.addActionListener(actionListener);

        deleteInvoicebtn.setText("Delete Invoice");
        deleteInvoicebtn.addActionListener(actionListener);

        jLabel1.setText("Invoice Num");

        jLabel2.setText("Invoice Date");

        jLabel3.setText("Customer Name");

        jLabel4.setText("Invoice Total");

        InvoicedetailLabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(InvoicedetailLabel);

        createNewLinebtn.setText("New Line");
        createNewLinebtn.addActionListener(actionListener);

        deleteLinebtn.setText("Delete Line");
        deleteLinebtn.addActionListener(actionListener);

        jMenu1.setText("File");

        LoadoptionItem.setText("Load Files");
        LoadoptionItem.addActionListener(actionListener);
        jMenu1.add(LoadoptionItem);

        SaveoptionItem.setText("Save Files");
        SaveoptionItem.addActionListener(actionListener);
        jMenu1.add(SaveoptionItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InvoiceTotalLabel)
                            .addComponent(InvoiceNumLabel)
                            .addComponent(InvoiceDateLable)
                            .addComponent(cutomerNameLabel)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(CreateNewInvoicebtn)
                .addGap(67, 67, 67)
                .addComponent(deleteInvoicebtn)
                .addGap(136, 136, 136)
                .addComponent(createNewLinebtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteLinebtn)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(InvoiceNumLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(InvoiceDateLable))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cutomerNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(InvoiceTotalLabel))
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateNewInvoicebtn)
                    .addComponent(deleteInvoicebtn)
                    .addComponent(createNewLinebtn)
                    .addComponent(deleteLinebtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateNewInvoicebtn;
    private javax.swing.JLabel InvoiceDateLable;
    private javax.swing.JLabel InvoiceNumLabel;
    private javax.swing.JTable InvoiceTableMain;
    private javax.swing.JLabel InvoiceTotalLabel;
    private javax.swing.JTable InvoicedetailLabel;
    private javax.swing.JMenuItem LoadoptionItem;
    private javax.swing.JMenuItem SaveoptionItem;
    private javax.swing.JButton createNewLinebtn;
    private javax.swing.JLabel cutomerNameLabel;
    private javax.swing.JButton deleteInvoicebtn;
    private javax.swing.JButton deleteLinebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    private ListenerOnInvoices actionListener = new ListenerOnInvoices(this);
    private ArrayList<HeaderOfInvoice> invoicesArray;
    private ArrayList<LinesOfInvoice> linesArray;
    private HeaderOfInvoiceTableModel headerTableModel;
    public static SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
    private ListenerOnTableSelection selectionListener = new ListenerOnTableSelection(this);

    public ArrayList<LinesOfInvoice> getLinesArray() {
        return linesArray;
    }

    public void setLinesArray(ArrayList<LinesOfInvoice> linesArray) {
        this.linesArray = linesArray;
    }
    
    public void setInvoicesArray(ArrayList<HeaderOfInvoice> invoicesArray) {
        this.invoicesArray = invoicesArray;
    }

    public ArrayList<HeaderOfInvoice> getInvoicesArray() {
        return invoicesArray;
    }
    
    public HeaderOfInvoice getInvObject(int code) {
        for (HeaderOfInvoice inv : invoicesArray) {
            if (inv.getNumberr() == code) {
                return inv;
            }
        }
        return null;
    }

    public HeaderOfInvoiceTableModel getHeaderTableModel() {
        return headerTableModel;
    }

    public void setHeaderTableModel(HeaderOfInvoiceTableModel headerTableModel) {
        this.headerTableModel = headerTableModel;
    }

    public JTable getInvoiceTableMain() {
        return InvoiceTableMain;
    }

    public JTable getInvoicedetailLabel() {
        return InvoicedetailLabel;
    }

    public JLabel getCutomerNameLabel() {
        return cutomerNameLabel;
    }

    public JLabel getInvoiceDateLable() {
        return InvoiceDateLable;
    }

    public JLabel getInvoiceNumLabel() {
        return InvoiceNumLabel;
    }

    public JLabel getInvoiceTotalLabel() {
        return InvoiceTotalLabel;
    }

    public ListenerOnInvoices getActionListener() {
        return actionListener;
    }
    
    
}
